### ISSUE TITLE
rospy.exceptions.ROSException: timeout exceeded while waiting for service /pedsim_simulator/spawn_interactive_obstacles

### ISSUE THREAD

**Issue by ll7** [ignc-research/arena-rosnav#52]
Any ideas what is going wrong?

```bash
roslaunch arena_bringup start_arena_flatland.launch
... logging to /root/.ros/log/84e550f4-cd12-11ec-ac59-0242ac130003/roslaunch-d5247af3bda6-2629.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://d5247af3bda6:35995/

SUMMARY
========

PARAMETERS
 * /action_frequency: 10
 * /inter_planner/astar/allocate_num: 100000
 * /inter_planner/astar/lambda_heu: 0.1
 * /inter_planner/astar/resolution_astar: 0.1
 * /inter_planner/astar/time_resolution: 0.8
 * /inter_planner/b_spline/control_points_distance: 0.5
 * /inter_planner/b_spline/feasibility_tolerance: 0.05
 * /inter_planner/b_spline/max_acc: 2.0
 * /inter_planner/b_spline/max_jerk: 4.0
 * /inter_planner/b_spline/max_vel: 3.0
 * /inter_planner/b_spline/planning_horizon: 7.5
 * /inter_planner/global_planner/dist_next_wp: 3.0
 * /inter_planner/global_planner/dist_tolerance: 1.0
 * /inter_planner/global_planner/rou_thresh: 15.0
 * /inter_planner/global_planner/use_astar: True
 * /inter_planner/global_planner/use_kino_astar: True
 * /inter_planner/global_planner/use_oneshot: True
 * /inter_planner/global_planner/use_optimization_astar: True
 * /inter_planner/global_planner/use_optimization_esdf: True
 * /inter_planner/kino_astar/allocate_num: 100000
 * /inter_planner/kino_astar/check_num: 5
 * /inter_planner/kino_astar/horizon: 30
 * /inter_planner/kino_astar/init_max_tau: 0.8
 * /inter_planner/kino_astar/lambda_heu: 0.1
 * /inter_planner/kino_astar/max_acc: 2.0
 * /inter_planner/kino_astar/max_tau: 0.6
 * /inter_planner/kino_astar/max_vel: 3.0
 * /inter_planner/kino_astar/resolution_astar: 0.1
 * /inter_planner/kino_astar/time_resolution: 0.8
 * /inter_planner/kino_astar/w_time: 10.0
 * /inter_planner/optimization_ESDF/algorithm1: 15
 * /inter_planner/optimization_ESDF/algorithm2: 11
 * /inter_planner/optimization_ESDF/dist0: 0.4
 * /inter_planner/optimization_ESDF/lambda1: 10.0
 * /inter_planner/optimization_ESDF/lambda2: 5.0
 * /inter_planner/optimization_ESDF/lambda3: 1e-05
 * /inter_planner/optimization_ESDF/lambda4: 0.01
 * /inter_planner/optimization_ESDF/lambda5: 1.5
 * /inter_planner/optimization_ESDF/lambda6: 10.0
 * /inter_planner/optimization_ESDF/lambda7: 100.0
 * /inter_planner/optimization_ESDF/max_acc: 2.0
 * /inter_planner/optimization_ESDF/max_iteration_num1: 2
 * /inter_planner/optimization_ESDF/max_iteration_num2: 300
 * /inter_planner/optimization_ESDF/max_iteration_num3: 200
 * /inter_planner/optimization_ESDF/max_iteration_num4: 200
 * /inter_planner/optimization_ESDF/max_iteration_time1: 0.0001
 * /inter_planner/optimization_ESDF/max_iteration_time2: 0.005
 * /inter_planner/optimization_ESDF/max_iteration_time3: 0.003
 * /inter_planner/optimization_ESDF/max_iteration_time4: 0.003
 * /inter_planner/optimization_ESDF/max_vel: 3.0
 * /inter_planner/optimization_ESDF/order: 3
 * /inter_planner/optimization_astar/dist0: 0.5
 * /inter_planner/optimization_astar/lambda_collision: 0.5
 * /inter_planner/optimization_astar/lambda_feasibility: 0.1
 * /inter_planner/optimization_astar/lambda_fitness: 1.0
 * /inter_planner/optimization_astar/lambda_smooth: 1.0
 * /inter_planner/optimization_astar/max_acc: 2.0
 * /inter_planner/optimization_astar/max_vel: 3.0
 * /inter_planner/optimization_astar/order: 3
 * /inter_planner/sdf_map/frame_id: map
 * /inter_planner/sdf_map/local_bound_inflate: 0.0
 * /inter_planner/sdf_map/local_map_margin: 50.0
 * /inter_planner/sdf_map/local_update_range_x: 10.0
 * /inter_planner/sdf_map/local_update_range_y: 10.0
 * /inter_planner/sdf_map/max_ray_length: 10.0
 * /inter_planner/sdf_map/min_ray_length: 0.5
 * /inter_planner/sdf_map/obstacles_inflation: 0.3
 * /inter_planner/sdf_map/p_hit: 0.55
 * /inter_planner/sdf_map/p_max: 0.8
 * /inter_planner/sdf_map/p_min: 0.12
 * /inter_planner/sdf_map/p_miss: 0.2
 * /inter_planner/sdf_map/p_occ: 0.7
 * /inter_planner/sdf_map/resolution: 0.05
 * /inter_planner/sdf_map/show_esdf_time: False
 * /inter_planner/sdf_map/show_occ_time: False
 * /inter_planner/sdf_map/use_occ_esdf: True
 * /laser_update_rate: 10
 * /local_planner: teb
 * /map_file: ignc
 * /map_layer_path: /root/arena_ws/sr...
 * /map_server/frame_id: map
 * /model: burger
 * /move_base/DWAPlannerROS/acc_lim_theta: 3.2
 * /move_base/DWAPlannerROS/acc_lim_x: 2.5
 * /move_base/DWAPlannerROS/acc_lim_y: 0.0
 * /move_base/DWAPlannerROS/controller_frequency: 10.0
 * /move_base/DWAPlannerROS/forward_point_distance: 0.325
 * /move_base/DWAPlannerROS/goal_distance_bias: 20.0
 * /move_base/DWAPlannerROS/latch_xy_goal_tolerance: False
 * /move_base/DWAPlannerROS/max_scaling_factor: 0.2
 * /move_base/DWAPlannerROS/max_vel_theta: 2.75
 * /move_base/DWAPlannerROS/max_vel_trans: 0.22
 * /move_base/DWAPlannerROS/max_vel_x: 0.22
 * /move_base/DWAPlannerROS/max_vel_y: 0.0
 * /move_base/DWAPlannerROS/min_vel_theta: 1.37
 * /move_base/DWAPlannerROS/min_vel_trans: 0.11
 * /move_base/DWAPlannerROS/min_vel_x: -0.22
 * /move_base/DWAPlannerROS/min_vel_y: 0.0
 * /move_base/DWAPlannerROS/occdist_scale: 0.02
 * /move_base/DWAPlannerROS/oscillation_reset_dist: 0.05
 * /move_base/DWAPlannerROS/path_distance_bias: 32.0
 * /move_base/DWAPlannerROS/publish_cost_grid_pc: True
 * /move_base/DWAPlannerROS/publish_traj_pc: True
 * /move_base/DWAPlannerROS/scaling_speed: 0.25
 * /move_base/DWAPlannerROS/sim_time: 1.5
 * /move_base/DWAPlannerROS/stop_time_buffer: 0.2
 * /move_base/DWAPlannerROS/vth_samples: 40
 * /move_base/DWAPlannerROS/vx_samples: 20
 * /move_base/DWAPlannerROS/vy_samples: 0
 * /move_base/DWAPlannerROS/xy_goal_tolerance: 0.05
 * /move_base/DWAPlannerROS/yaw_goal_tolerance: 0.17
 * /move_base/TebLocalPlannerROS/acc_lim_theta: 0.5
 * /move_base/TebLocalPlannerROS/acc_lim_x: 0.5
 * /move_base/TebLocalPlannerROS/allow_init_with_backwards_motion: False
 * /move_base/TebLocalPlannerROS/complete_global_plan: True
 * /move_base/TebLocalPlannerROS/costmap_converter_plugin: 
 * /move_base/TebLocalPlannerROS/costmap_converter_rate: 5
 * /move_base/TebLocalPlannerROS/costmap_converter_spin_thread: True
 * /move_base/TebLocalPlannerROS/costmap_obstacles_behind_robot_dist: 1.5
 * /move_base/TebLocalPlannerROS/delete_detours_backwards: True
 * /move_base/TebLocalPlannerROS/dt_hysteresis: 0.1
 * /move_base/TebLocalPlannerROS/dt_ref: 0.3
 * /move_base/TebLocalPlannerROS/dynamic_obstacle_inflation_dist: 0.6
 * /move_base/TebLocalPlannerROS/enable_homotopy_class_planning: True
 * /move_base/TebLocalPlannerROS/enable_multithreading: True
 * /move_base/TebLocalPlannerROS/exact_arc_length: False
 * /move_base/TebLocalPlannerROS/feasibility_check_no_poses: 5
 * /move_base/TebLocalPlannerROS/footprint_model/type: point
 * /move_base/TebLocalPlannerROS/free_goal_vel: False
 * /move_base/TebLocalPlannerROS/global_plan_overwrite_orientation: True
 * /move_base/TebLocalPlannerROS/global_plan_prune_distance: 1
 * /move_base/TebLocalPlannerROS/global_plan_viapoint_sep: -1
 * /move_base/TebLocalPlannerROS/h_signature_prescaler: 0.5
 * /move_base/TebLocalPlannerROS/h_signature_threshold: 0.1
 * /move_base/TebLocalPlannerROS/include_costmap_obstacles: True
 * /move_base/TebLocalPlannerROS/include_dynamic_obstacles: True
 * /move_base/TebLocalPlannerROS/inflation_dist: 0.6
 * /move_base/TebLocalPlannerROS/max_global_plan_lookahead_dist: 3.0
 * /move_base/TebLocalPlannerROS/max_number_classes: 4
 * /move_base/TebLocalPlannerROS/max_ratio_detours_duration_best_duration: 3.0
 * /move_base/TebLocalPlannerROS/max_samples: 500
 * /move_base/TebLocalPlannerROS/max_vel_theta: 0.3
 * /move_base/TebLocalPlannerROS/max_vel_x: 0.22
 * /move_base/TebLocalPlannerROS/max_vel_x_backwards: 0.2
 * /move_base/TebLocalPlannerROS/max_vel_y: 0.0
 * /move_base/TebLocalPlannerROS/min_obstacle_dist: 0.25
 * /move_base/TebLocalPlannerROS/min_turning_radius: 0.0
 * /move_base/TebLocalPlannerROS/no_inner_iterations: 5
 * /move_base/TebLocalPlannerROS/no_outer_iterations: 4
 * /move_base/TebLocalPlannerROS/obstacle_cost_exponent: 4
 * /move_base/TebLocalPlannerROS/obstacle_heading_threshold: 0.45
 * /move_base/TebLocalPlannerROS/obstacle_poses_affected: 15
 * /move_base/TebLocalPlannerROS/odom_topic: odom
 * /move_base/TebLocalPlannerROS/optimization_activate: True
 * /move_base/TebLocalPlannerROS/optimization_verbose: False
 * /move_base/TebLocalPlannerROS/oscillation_filter_duration: 10
 * /move_base/TebLocalPlannerROS/oscillation_omega_eps: 0.1
 * /move_base/TebLocalPlannerROS/oscillation_recovery: True
 * /move_base/TebLocalPlannerROS/oscillation_recovery_min_duration: 10
 * /move_base/TebLocalPlannerROS/oscillation_v_eps: 0.1
 * /move_base/TebLocalPlannerROS/penalty_epsilon: 0.1
 * /move_base/TebLocalPlannerROS/publish_feedback: False
 * /move_base/TebLocalPlannerROS/roadmap_graph_area_length_scale: 1.0
 * /move_base/TebLocalPlannerROS/roadmap_graph_area_width: 5
 * /move_base/TebLocalPlannerROS/roadmap_graph_no_samples: 15
 * /move_base/TebLocalPlannerROS/selection_alternative_time_cost: False
 * /move_base/TebLocalPlannerROS/selection_cost_hysteresis: 1.0
 * /move_base/TebLocalPlannerROS/selection_obst_cost_scale: 100.0
 * /move_base/TebLocalPlannerROS/selection_prefer_initial_plan: 0.9
 * /move_base/TebLocalPlannerROS/shrink_horizon_backup: True
 * /move_base/TebLocalPlannerROS/shrink_horizon_min_duration: 10
 * /move_base/TebLocalPlannerROS/switching_blocking_period: 0.0
 * /move_base/TebLocalPlannerROS/teb_autosize: True
 * /move_base/TebLocalPlannerROS/viapoints_all_candidates: True
 * /move_base/TebLocalPlannerROS/visualize_hc_graph: False
 * /move_base/TebLocalPlannerROS/visualize_with_time_as_z_axis_scale: False
 * /move_base/TebLocalPlannerROS/weight_acc_lim_theta: 1
 * /move_base/TebLocalPlannerROS/weight_acc_lim_x: 1
 * /move_base/TebLocalPlannerROS/weight_adapt_factor: 2
 * /move_base/TebLocalPlannerROS/weight_dynamic_obstacle: 10
 * /move_base/TebLocalPlannerROS/weight_dynamic_obstacle_inflation: 0.2
 * /move_base/TebLocalPlannerROS/weight_inflation: 0.2
 * /move_base/TebLocalPlannerROS/weight_kinematics_forward_drive: 1
 * /move_base/TebLocalPlannerROS/weight_kinematics_nh: 1000
 * /move_base/TebLocalPlannerROS/weight_kinematics_turning_radius: 1
 * /move_base/TebLocalPlannerROS/weight_max_vel_theta: 1
 * /move_base/TebLocalPlannerROS/weight_max_vel_x: 2
 * /move_base/TebLocalPlannerROS/weight_obstacle: 100
 * /move_base/TebLocalPlannerROS/weight_optimaltime: 1
 * /move_base/TebLocalPlannerROS/weight_shortest_path: 0
 * /move_base/TebLocalPlannerROS/weight_viapoint: 1
 * /move_base/TebLocalPlannerROS/xy_goal_tolerance: 0.2
 * /move_base/TebLocalPlannerROS/yaw_goal_tolerance: 0.1
 * /move_base/base_local_planner: teb_local_planner...
 * /move_base/controller_frequency: 5.0
 * /move_base/controller_patience: 15.0
 * /move_base/global_costmap/cost_scaling_factor: 3.0
 * /move_base/global_costmap/footprint: [[-0.105, -0.105]...
 * /move_base/global_costmap/global_frame: map
 * /move_base/global_costmap/inflation_radius: 1.0
 * /move_base/global_costmap/map_type: costmap
 * /move_base/global_costmap/observation_sources: scan
 * /move_base/global_costmap/obstacle_range: 3.0
 * /move_base/global_costmap/publish_frequency: 10.0
 * /move_base/global_costmap/raytrace_range: 3.5
 * /move_base/global_costmap/robot_base_frame: base_footprint
 * /move_base/global_costmap/scan/clearing: True
 * /move_base/global_costmap/scan/data_type: LaserScan
 * /move_base/global_costmap/scan/marking: True
 * /move_base/global_costmap/scan/sensor_frame: laser_link
 * /move_base/global_costmap/scan/topic: scan
 * /move_base/global_costmap/static_map: True
 * /move_base/global_costmap/transform_tolerance: 0.5
 * /move_base/global_costmap/update_frequency: 10.0
 * /move_base/local_costmap/cost_scaling_factor: 3.0
 * /move_base/local_costmap/footprint: [[-0.105, -0.105]...
 * /move_base/local_costmap/global_frame: odom
 * /move_base/local_costmap/height: 3
 * /move_base/local_costmap/inflation_radius: 1.0
 * /move_base/local_costmap/map_type: costmap
 * /move_base/local_costmap/observation_sources: scan
 * /move_base/local_costmap/obstacle_range: 3.0
 * /move_base/local_costmap/publish_frequency: 10.0
 * /move_base/local_costmap/raytrace_range: 3.5
 * /move_base/local_costmap/resolution: 0.05
 * /move_base/local_costmap/robot_base_frame: base_footprint
 * /move_base/local_costmap/rolling_window: True
 * /move_base/local_costmap/scan/clearing: True
 * /move_base/local_costmap/scan/data_type: LaserScan
 * /move_base/local_costmap/scan/marking: True
 * /move_base/local_costmap/scan/sensor_frame: laser_link
 * /move_base/local_costmap/scan/topic: scan
 * /move_base/local_costmap/static_map: False
 * /move_base/local_costmap/transform_tolerance: 0.5
 * /move_base/local_costmap/update_frequency: 10.0
 * /move_base/local_costmap/width: 3
 * /move_base/planner_frequency: 1.0
 * /obs_vel: 0.3
 * /pedsim_simulator/pedsim_update_rate: 30.0
 * /pedsim_simulator/scene_file: /root/arena_ws/sr...
 * /pedsim_simulator/simulation_factor: 1.0
 * /plan_manager/look_ahead_distance: 2.3
 * /plan_manager/timeout_goal: 330.0
 * /plan_manager/timeout_subgoal: 20
 * /plan_manager/tolerance_approach: 0.6
 * /plan_manager/train_mode: False
 * /radius: 0.113
 * /robot_action_rate: 5
 * /rosdistro: noetic
 * /rosversion: 1.15.14
 * /show_viz: True
 * /single_env: True
 * /speed: 0.22
 * /step_size: 0.01
 * /task_generator_node/auto_reset: True
 * /task_generator_node/delta: 1.0
 * /task_generator_node/scenarios_json_path: /root/arena_ws/sr...
 * /task_generator_node/task_mode: scenario
 * /task_generator_node/timeout: 3.0
 * /train_mode: False
 * /update_rate: 500
 * /use_rviz: True
 * /use_sim_time: True
 * /viz_pub_rate: 30
 * /world_path: /root/arena_ws/sr...

NODES
  /
    flatland_rviz (rviz/rviz)
    flatland_server (flatland_server/flatland_server)
    inter_planner (arena_intermediate_planner/arena_intermediate_planner)
    map_server (map_server/map_server)
    map_to_odom_tfpublisher (tf2_ros/static_transform_publisher)
    move_base (move_base/move_base)
    pedsim_simulator (pedsim_simulator/pedsim_simulator)
    plan_manager (arena_plan_manager/plan_manager_node)
    spawn_model (rosservice/rosservice)
    task_generator_node (task_generator/task_generator_node.py)
  /sensorsim/
    sensorsim_node (sensor_simulator/sensorsim_node_tmgr.py)

auto-starting new master
process[master]: started with pid [2644]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 84e550f4-cd12-11ec-ac59-0242ac130003
process[rosout-1]: started with pid [2660]
started core service [/rosout]
process[flatland_server-2]: started with pid [2667]
process[spawn_model-3]: started with pid [2668]
process[flatland_rviz-4]: started with pid [2669]
process[map_server-5]: started with pid [2670]
process[map_to_odom_tfpublisher-6]: started with pid [2671]
process[task_generator_node-7]: started with pid [2672]
process[sensorsim/sensorsim_node-8]: started with pid [2673]
process[move_base-9]: started with pid [2674]
process[plan_manager-10]: started with pid [2679]
process[inter_planner-11]: started with pid [2681]
[ INFO] [1651823997.155403848]: waitForService: Service [/global_kino_make_plan] has not been advertised, waiting...
process[pedsim_simulator-12]: started with pid [2682]
start
[ INFO] [1651823997.188061405]: waitForService: Service [/static_map] has not been advertised, waiting...
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[ INFO] [1651823997.319684030]: rviz version 1.14.14
[ INFO] [1651823997.319722830]: compiled against Qt version 5.12.8
[ INFO] [1651823997.319733290]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1651823997.322569955]: Updated sim with live config: Rate=24 incoming rate=24
[ INFO] [1651823997.329627631]: Forcing OpenGl version 0.
[ INFO] [1651823997.342950420]: Using default queue size of 1 for publisher queues... 
[ INFO] [1651823997.362650769]: Simulation params: world_yaml_file(/root/arena_ws/src/arena-rosnav/simulator_setup/maps/ignc/map.world.yaml), map_layer_yaml_file(/root/arena_ws/src/arena-rosnav/simulator_setup/maps/ignc/map_layer.yaml), map_file(ignc), update_rate(500.000000), step_size(0.010000) show_viz(true), viz_pub_rate(30.000000)
[ INFO] [1651823997.364142127]: Initialized
[ INFO] [1651823997.364166767]: Initializing...
[ INFO] [1651823997.364998111]: Loading scene [/root/arena_ws/src/arena-rosnav/simulator_setup/scenarios/empty.xml] for simulation
[ INFO] [1651823997.367669315]: created agent with id: 1
[ INFO] [1651823997.423675512]: Loading layer "static" from path="/root/arena_ws/src/arena-rosnav/simulator_setup/maps/ignc/map.yaml"
[ INFO] [1651823997.423840983]: layer "static" loading image from path="/root/arena_ws/src/arena-rosnav/simulator_setup/maps/ignc/map.pgm"
[ INFO] [1651823997.430108886]: Layer "static" loaded
[ INFO] [1651823997.430163396]: Leaving active layer "static"
[ INFO] [1651823997.430198316]: World loaded
[ INFO] [1651823997.431393892]: Visualizing layer/static
[ INFO] [1651823997.434384558]: Model spawning service ready to go
[ INFO] [1651823997.434409208]: Model deleting service ready to go
[ INFO] [1651823997.434422858]: Model moving service ready to go
[ INFO] [1651823997.434441878]: Simulation loop started
[ INFO] [1651823997.668255696, 1.180000000]: Loading model from path="/root/arena_ws/src/arena-rosnav/simulator_setup/robot/burger.model.yaml"
[ INFO] [1651823997.678294377, 1.180000000]: Model Plugin "diff_drive" type "DiffDrive" model "burger" loaded
[ INFO] [1651823997.678886930, 1.180000000]: Laser plugin loaded with 13 threads
[ INFO] [1651823997.679364123, 1.180000000]: Model Plugin "static_laser" type "Laser" model "burger" loaded
[ INFO] [1651823997.679459553, 1.180000000]: Model Plugin "tf_publisher" type "ModelTfPublisher" model "burger" loaded
[ INFO] [1651823997.679557684, 1.180000000]: Model "burger" loaded
[ INFO] [1651823997.735483101]: Stereo is NOT SUPPORTED
[ INFO] [1651823997.735547061]: OpenGL device: llvmpipe (LLVM 12.0.0, 256 bits)
[ INFO] [1651823997.735568231]: OpenGl version: 3.1 (GLSL 1.4).
======================================== reset:0
dynamic obstacles: 0
[ INFO] [1651823997.772829901]: waitForService: Service [/static_map] is now available.
[ INFO] [1651823997.773636355]: Is stacic map available: True
use_occ_esdf: 1
x_size: 25
y_size: 25
x_origin: -12.5
y_origin: -12.5
x_size_pix: 250
y_size_pix: 250
x_map_max_idx: 249
y_map_max_idx: 249
x_local_update_range_: 10
y_local_update_range_: 10
hit: 0.200671
miss: -1.38629
min log: -1.99243
max: 1.38629
thresh log: 0.847298
dist_next_wp_=3
lambda_heu_:0.1
origin_: -12.5 -12.5
map size: 25 25
origin_: -12.5 -12.5
map size: 25 25
[ERROR] [1651823997.831150571, 1.900000000]: Failed to load model! Exception: Flatland YAML: Model with name "burger" already exists
[ INFO] [1651823997.861979799, 2.020000000]: waitForService: Service [/global_kino_make_plan] is now available.
[ WARN] [1651823997.870575213, 2.100000000]: Map I got is empty. Timeout? Trying again.
[ WARN] [1651823997.971485830, 2.600000000]: global_costmap: Parameter "plugins" not provided, loading pre-Hydro parameters
[ INFO] [1651823997.987879274, 2.690000000]: global_costmap: Using plugin "static_layer"
[ INFO] [1651823997.995224412, 2.720000000]: Requesting the map...
[ INFO] [1651823998.002775641, 2.760000000]: Got map h x w: 250 x 250
[ INFO] [1651823998.005628035, 2.770000000]: node initialized, now running 
[ INFO] [1651823998.173478034, 3.600000000]: SpawnModelTool::SetMovingModelColor
[ WARN] [1651823998.173892186, 3.600000000]: OGRE EXCEPTION(2:InvalidParametersException): Object index out of bounds. in SceneNode::getAttachedObject at /build/ogre-1.9-kiU5_5/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreSceneNode.cpp (line 160)
[ WARN] [1651823998.174408709, 3.600000000]: Invalid preview model
[ INFO] [1651823998.239270882, 3.900000000]: Creating 1 swatches
[ INFO] [1651823998.266981854, 4.030000000]: Resizing costmap to 250 X 250 at 0.100000 m/pix
[ INFO] [1651823998.287384018, 4.130000000]: Received a 250 X 250 map at 0.100000 m/pix
[ INFO] [1651823998.289463888, 4.140000000]: global_costmap: Using plugin "obstacle_layer"
[ INFO] [1651823998.291316788, 4.150000000]:     Subscribed to Topics: scan
[ INFO] [1651823998.302320365, 4.200000000]: global_costmap: Using plugin "inflation_layer"
[ WARN] [1651823998.326278798, 4.320000000]: local_costmap: Parameter "plugins" not provided, loading pre-Hydro parameters
[ INFO] [1651823998.333377124, 4.360000000]: local_costmap: Using plugin "obstacle_layer"
[ INFO] [1651823998.335072613, 4.370000000]:     Subscribed to Topics: scan
[spawn_model-3] process has finished cleanly
log file: /root/.ros/log/84e550f4-cd12-11ec-ac59-0242ac130003/spawn_model-3*.log
[ INFO] [1651823998.344078109, 4.410000000]: local_costmap: Using plugin "inflation_layer"
[ INFO] [1651823998.370998977, 4.540000000]: Created local_planner teb_local_planner/TebLocalPlannerROS
[ INFO] [1651823998.409368333, 4.730000000]: Footprint model 'point' loaded for trajectory optimization.
[ INFO] [1651823998.409442293, 4.730000000]: Parallel planning in distinctive topologies enabled.
[ INFO] [1651823998.409479033, 4.730000000]: No costmap conversion plugin specified. All occupied costmap cells are treaten as point obstacles.
[ INFO] [1651823998.453104607, 4.950000000]: Footprint model 'point' loaded for trajectory optimization.
[ INFO] [1651823998.506385351, 5.210000000]: Recovery behavior will clear layer 'obstacles'
[ INFO] [1651823998.510118700, 5.230000000]: Recovery behavior will clear layer 'obstacles'
[ INFO] [1651823998.623072879, 5.800000000]: odom received!
[ INFO] [1651823998.631596113, 5.840000000]: Creating 1 swatches
[ INFO] [1651823998.632074625, 5.840000000]: Creating 1 swatches
Traceback (most recent call last):
  File "/root/arena_ws/src/arena-rosnav/task_generator/scripts/task_generator_node.py", line 120, in <module>
    task_generator = TaskGenerator()
  File "/root/arena_ws/src/arena-rosnav/task_generator/scripts/task_generator_node.py", line 23, in __init__
    self.task = get_predefined_task("",mode, PATHS=paths)
  File "/root/arena_ws/src/arena-rosnav/task_generator/task_generator/tasks.py", line 724, in get_predefined_task
    task = ScenarioTask(
  File "/root/arena_ws/src/arena-rosnav/task_generator/task_generator/tasks.py", line 602, in __init__
    self.pedsim_manager = PedsimManager()
  File "/root/arena_ws/src/arena-rosnav/task_generator/task_generator/tasks.py", line 545, in __init__
    rospy.wait_for_service(pawn_interactive_obstacles_service_name, 6.0)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 148, in wait_for_service
    raise ROSException("timeout exceeded while waiting for service %s"%resolved_name)
rospy.exceptions.ROSException: timeout exceeded while waiting for service /pedsim_simulator/spawn_interactive_obstacles
[task_generator_node-7] process has died [pid 2672, exit code 1, cmd /root/arena_ws/src/arena-rosnav/task_generator/scripts/task_generator_node.py __name:=task_generator_node __log:=/root/.ros/log/84e550f4-cd12-11ec-ac59-0242ac130003/task_generator_node-7.log].
log file: /root/.ros/log/84e550f4-cd12-11ec-ac59-0242ac130003/task_generator_node-7*.log
```

**Comment by harshmahesheka** [comment]
Same error, did you find any solution?

**Comment by ll7** [comment]
No. Sorry.

**Comment by Ducanor** [comment]
Did this error still prevail?
There were some issues with the pedsim module.
Did you try the [common error handling procedures](https://github.com/ignc-research/arena-rosnav/blob/local_planner_subgoalmode/docs/guide.md#common-error-handling)?

**Comment by harshmahesheka** [comment]
I tried it didn't solve.I tried docker it was also not working but then I used docker created by @ll7 and it worked. So, thanks!
